[build]
  command = "npm i && cd api && npm i && cd ../ui-react && npm i && cd .. && npm run build && cp api/build/graphql-schema.js api/build/functions/graphql/. && cp api/build/schema.graphql api/build/functions/graphql/.  && cd api/src/functions/graphql && npm i"
  publish = "ui-react/build"
  functions = "api/build/functions"

[dev]
  command = "npm start"

[template.environment]
  NEO4J_URI = "bolt://localhost:7687"
  NEO4J_USER = "neo4j"
  NEO4J_PASSWORD = "letmein"
  
[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200